### ISSUE TITLE
EXPORT_FOLDER doesn't support absolute paths

### ISSUE THREAD

**Issue by RadekCap** [rh-openjdk/WindowsTPS#29]
It was tested locally, but for Adoptium we need to be working with absolute paths.

See https://github.com/adoptium/installer/issues/559

`export 'RESULTS_FOLDER=/cygdrive/e/workspace/Windows_Installer_Test/aqa-tests/functional/wintps/WindowsTPS/wrapper/../E:/workspace/Windows_Installer_Test/aqa-tests/\TKG\output_16775375532924\WinTPSTests_0/result'`

**Comment by zzambers** [comment]
@RadekCap  I commented on the same thing in PR fixing _INPUT. It can be fixed by canonizing paths, see:
https://github.com/rh-openjdk/WindowsTPS/pull/27#issuecomment-1450712766

**Comment by zzambers** [comment]
Problem is following. Testsuite internally does not like relative paths. That's probably why workaround with interpreting them relative to script location was done (prefix is added to configured paths). This however, apart from being confusing also does not work, if absolute paths are configured. Doing canonization instead, will make this work with both absolute and relative paths.

**Comment by RadekCap** [comment]
Fixed by #30
